_wandb:
    value:
        cli_version: 0.21.4
        e:
            ctrjurlv7t1vct1gpi7cyflcbzpr0p2c:
                args:
                    - --model-config
                    - model_config.yaml
                    - --train-config
                    - train_config.yaml
                    - --wandb-run-name
                    - seq2seq-large
                codePath: part1\train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "492648263680"
                        used: "406853967872"
                email: lord54076@gmail.com
                executable: C:\Users\mhdih\OneDrive\Desktop\work\cw2_nlp\.venv312\Scripts\python.exe
                git:
                    commit: bf40bd8efb135beebcdf51290196426238c1c5ff
                    remote: https://github.com/lostithi/cw2_nlp.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-fb749ffd-4a60-6c76-affa-1d34cee72097
                host: MSI
                memory:
                    total: "8403050496"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\mhdih\OneDrive\Desktop\work\cw2_nlp\part1\train.py
                python: CPython 3.12.7
                root: C:\Users\mhdih\OneDrive\Desktop\work\cw2_nlp\part1
                startedAt: "2025-11-28T01:26:28.703768Z"
                writerId: ctrjurlv7t1vct1gpi7cyflcbzpr0p2c
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 61
            "4": 3.12.7
            "5": 0.21.4
            "8":
                - 2
                - 3
            "12": 0.21.4
            "13": windows-amd64
dev_batch_size:
    value: 32
dropout_rate:
    value: 0.2
embed_size:
    value: 128
hidden_size:
    value: 128
log_every:
    value: 10
lr:
    value: 0.001
lr_decay:
    value: 0.5
max_epoch:
    value: 30
max_num_trial:
    value: 5
patience:
    value: 1
seed:
    value: 0
train_batch_size:
    value: 32
uniform_init:
    value: 0.1
valid_niter:
    value: 200
